export default {
    // COMMON
    SIDEBAR_TOGGLE: 'SIDEBAR_TOGGLE',
    NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
    NOTIFICATION_HIDE: 'NOTIFICATION_HIDE',

    // Modal
    MODAL_SHOW: 'MODAL_SHOW',
    MODAL_HIDE: 'MODAL_HIDE',

    // TABLE
    CHANGE_TABLE_SORT: 'CHANGE_TABLE_SORT',
    CHANGE_TABLE_ROWS: 'CHANGE_TABLE_ROWS',
    TABLE_ADD_FILTER: 'TABLE_ADD_FILTER',
    TABLE_REMOVE_FILTER: 'TABLE_REMOVE_FILTER',
    TABLE_REMOVE_ALL_FILTERS: 'TABLE_REMOVE_ALL_FILTERS',

    // TRACKING
    TRACKS_LOAD_REQUEST: 'TRACKS_LOAD_REQUEST',
    TRACKS_LOAD_SUCCESS: 'TRACKS_LOAD_SUCCESS',
    TRACK_ADD_REQUEST: 'TRACK_ADD_REQUEST',
    TRACK_ADD_SUCCESS: 'TRACK_ADD_SUCCESS',
    TRACK_DELETE_REQUEST: 'TRACK_DELETE_REQUEST',
    TRACK_DELETE_SUCCESS: 'TRACK_DELETE_SUCCESS',
    TRACK_UPDATE_REQUEST: 'TRACK_UPDATE_REQUEST',
    TRACK_UPDATE_SUCCESS: 'TRACK_UPDATE_SUCCESS',

    // AUTH
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCES: 'LOGIN_SUCCES',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

    // REGISTER
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    // PROFILE
    PROFILE_UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
    PROFILE_UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',

    // TASKS
    TASKS_REQUEST: 'TASKS_REQUEST',
    TASKS_SUCCESS: 'TASKS_SUCCESS',
    TASK_UPDATE_REQUEST: 'TASK_UPDATE_REQUEST',
    TASK_UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
    TASK_ADD_REQUEST: 'TASK_ADD_REQUEST',
    TASK_ADD_SUCCESS: 'TASK_ADD_SUCCESS',
    TASK_REMOVE_REQUEST: 'TASK_REMOVE_REQUEST',
    TASK_REMOVE_SUCCESS: 'TASK_REMOVE_SUCCESS',

    // USERS
    USERS_REQUEST: 'USERS_REQUEST',
    USERS_SUCCESS: 'USERS_SUCCESS',
    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_REMOVE_REQUEST: 'USER_REMOVE_REQUEST',
    USER_REMOVE_SUCCESS: 'USER_REMOVE_SUCCESS',
};