export const CHANGE_TABLE_SORT = 'CHANGE_TABLE_SORT';
export const CHANGE_TABLE_ROWS = 'CHANGE_TABLE_ROWS';
export const TABLE_SET_FILTER = 'TABLE_SET_FILTER';
export const TABLE_REMOVE_FILTER = 'TABLE_REMOVE_FILTER';
export const TABLE_REMOVE_ALL_FILTERS = 'TABLE_REMOVE_ALL_FILTERS';