export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAILURE = 'TASKS_FAILURE';

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAILURE = 'TASK_UPDATE_FAILURE';

export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAILURE = 'TASK_ADD_FAILURE';

export const TASK_REMOVE_REQUEST = 'TASK_REMOVE_REQUEST';
export const TASK_REMOVE_SUCCESS = 'TASK_REMOVE_SUCCESS';
export const TASK_REMOVE_FAILURE = 'TASK_REMOVE_FAILURE';