export const TRACKS_LOAD_REQUEST = 'TRACKS_LOAD_REQUEST';
export const TRACKS_LOAD_SUCCESS = 'TRACKS_LOAD_SUCCESS';
export const TRACKS_LOAD_FAILURE = 'TRACKS_LOAD_FAILURE';

export const TRACK_ADD_REQUEST = 'TRACK_ADD_REQUEST';
export const TRACK_ADD_SUCCESS = 'TRACK_ADD_SUCCESS';
export const TRACK_ADD_FAILURE = 'TRACK_ADD_FAILURE';

export const TRACK_DELETE_REQUEST = 'TRACK_DELETE_REQUEST';
export const TRACK_DELETE_SUCCESS = 'TRACK_DELETE_SUCCESS';
export const TRACK_DELETE_FAILURE = 'TRACK_DELETE_FAILURE';

export const TRACK_UPDATE_REQUEST = 'TRACK_UPDATE_REQUEST';
export const TRACK_UPDATE_SUCCESS = 'TRACK_UPDATE_SUCCESS';
export const TRACK_UPDATE_FAILURE = 'TRACK_UPDATE_FAILURE';